import {CauseRejetDemandeRdvCriteria} from './CauseRejetDemandeRdvCriteria.model';
import {TemplateEmailConfirmationCriteria} from './TemplateEmailConfirmationCriteria.model';
import {CentreHospitalierUniversitaireCriteria} from './CentreHospitalierUniversitaireCriteria.model';
import {PatientCriteria} from './PatientCriteria.model';
import {HopitalCriteria} from './HopitalCriteria.model';
import {UniteAdministrativeCriteria} from './UniteAdministrativeCriteria.model';
import {OperateurCriteria} from './OperateurCriteria.model';
import {StatusRdvCriteria} from './StatusRdvCriteria.model';
import {PrestationCriteria} from './PrestationCriteria.model';
import {BaseCriteria} from 'src/app/zynerator/criteria/BaseCriteria.model';


export class DemandeRdvCriteria  extends   BaseCriteria  {

    public id: number;
    public reference: string;
    public referenceLike: string;
    public ipp: string;
    public ippLike: string;
    public nom: string;
    public nomLike: string;
    public prenom: string;
    public prenomLike: string;
    public adresse: string;
    public adresseLike: string;
    public email: string;
    public emailLike: string;
    public cin: string;
    public cinLike: string;
    public codeRamed: string;
    public codeRamedLike: string;
    public observation: string;
    public observationLike: string;
    public ficheReferencePath: string;
    public ficheReferencePathLike: string;
    public dateDemandeRdv: Date;
    public dateDemandeRdvFrom: Date;
    public dateDemandeRdvTo: Date;
    public datePrevu: Date;
    public datePrevuFrom: Date;
    public datePrevuTo: Date;
    public dateEffective: Date;
    public dateEffectiveFrom: Date;
    public dateEffectiveTo: Date;
    public dateValidation: Date;
    public dateValidationFrom: Date;
    public dateValidationTo: Date;
    public dateRejet: Date;
    public dateRejetFrom: Date;
    public dateRejetTo: Date;
     public nombreReccurenceTotal: number;
     public nombreReccurenceTotalMin: number;
     public nombreReccurenceTotalMax: number;
     public nombreReccurenceValide: number;
     public nombreReccurenceValideMin: number;
     public nombreReccurenceValideMax: number;
     public nombreReccurenceRejet: number;
     public nombreReccurenceRejetMin: number;
     public nombreReccurenceRejetMax: number;
  public patient: PatientCriteria ;
  public patients: Array<PatientCriteria> ;
  public operateur: OperateurCriteria ;
  public operateurs: Array<OperateurCriteria> ;
  public centreHospitalierUniversitaire: CentreHospitalierUniversitaireCriteria ;
  public centreHospitalierUniversitaires: Array<CentreHospitalierUniversitaireCriteria> ;
  public hopital: HopitalCriteria ;
  public hopitals: Array<HopitalCriteria> ;
  public uniteAdministrative: UniteAdministrativeCriteria ;
  public uniteAdministratives: Array<UniteAdministrativeCriteria> ;
  public prestation: PrestationCriteria ;
  public prestations: Array<PrestationCriteria> ;
  public statusRdv: StatusRdvCriteria ;
  public statusRdvs: Array<StatusRdvCriteria> ;
  public causeRejetDemandeRdv: CauseRejetDemandeRdvCriteria ;
  public causeRejetDemandeRdvs: Array<CauseRejetDemandeRdvCriteria> ;
  public templateEmailConfirmation: TemplateEmailConfirmationCriteria ;
  public templateEmailConfirmations: Array<TemplateEmailConfirmationCriteria> ;

}
